site_name: Matthew
theme: readthedocs
site_author: Matthew
site_description: Matthew's Homepage


nav:
  - index.md
  - 推荐系统:
    - 推荐系统/论文阅读计划.md
  - 随笔:
    - 随笔/20240325复杂事情简单做.md
  - 关于博主:
    - 关于博主/自我介绍.md
