site_name: Matthew
theme: readthedocs
site_author: Matthew
site_description: Matthew's Homepage


nav:
  - index.md
  - Quant:
    - Quant/20240326自己搭建交易系统.md
    - Quant/20240327Quant基本知识.md
    - Quant/20240328Quant资料整理.md
  - LLM:
    - LLM/Survey.md
  - 推荐系统:
    - 推荐系统/22-23工作总结.md
  - 技术随笔:
    - 技术随笔/python3安装jupyter.md
    - 技术随笔/pytorch安装.md
  - 工作与生活:
    - 工作与生活/20240325复杂事情简单做.md
  - 关于博主:
    - 关于博主/自我介绍.md
